(tool-bar-mode -1)
(scroll-bar-mode -1)
(column-number-mode -1)
(line-number-mode -1)
(transient-mark-mode -1)
(menu-bar-mode -1)
(defun sb ()
  (interactive)
  (save-buffer)
  (message "saved %s" (buffer-name)))
(global-set-key (kbd "C-x C-s") 'sb)
(setq ring-bell-function 'ignore)       ; no beep
(setq visible-bell nil)
